return {
   -- -- Debugger (DAP) - muy útil para Python
   -- {
   --    "mfussenegger/nvim-dap",
   --    dependencies = {
   --       "rcarriga/nvim-dap-ui",
   --       "nvim-neotest/nvim-nio",
   --       "mfussenegger/nvim-dap-python",
   --    },
   --    config = function()
   --       local dap = require("dap")
   --       local dapui = require("dapui")
   --
   --       dapui.setup()
   --
   --       -- Configurar Python debugger
   --       require("dap-python").setup("python3")
   --
   --       -- Abrir/cerrar UI automáticamente
   --       dap.listeners.after.event_initialized["dapui_config"] = function()
   --          dapui.open()
   --       end
   --       dap.listeners.before.event_terminated["dapui_config"] = function()
   --          dapui.close()
   --       end
   --       dap.listeners.before.event_exited["dapui_config"] = function()
   --          dapui.close()
   --       end
   --
   --       -- Atajos de teclado para debugging
   --       vim.keymap.set("n", "<leader>db", dap.toggle_breakpoint, { desc = "Toggle breakpoint" })
   --       vim.keymap.set("n", "<leader>dc", dap.continue, { desc = "Debug continue" })
   --       vim.keymap.set("n", "<leader>di", dap.step_into, { desc = "Debug step into" })
   --       vim.keymap.set("n", "<leader>do", dap.step_over, { desc = "Debug step over" })
   --       vim.keymap.set("n", "<leader>dO", dap.step_out, { desc = "Debug step out" })
   --       vim.keymap.set("n", "<leader>dt", dapui.toggle, { desc = "Toggle debug UI" })
   --    end,
   -- },
   --
   -- -- Testing con Python (pytest, unittest)
   -- {
   --    "nvim-neotest/neotest",
   --    dependencies = {
   --       "nvim-neotest/nvim-nio",
   --       "nvim-lua/plenary.nvim",
   --       "nvim-treesitter/nvim-treesitter",
   --       "nvim-neotest/neotest-python",
   --    },
   --    config = function()
   --       require("neotest").setup({
   --          adapters = {
   --             require("neotest-python")({
   --                dap = { justMyCode = false },
   --                runner = "pytest",
   --             }),
   --          },
   --       })
   --
   --       vim.keymap.set("n", "<leader>tt", function()
   --          require("neotest").run.run()
   --       end, { desc = "Run nearest test" })
   --
   --       vim.keymap.set("n", "<leader>tf", function()
   --          require("neotest").run.run(vim.fn.expand("%"))
   --       end, { desc = "Run test file" })
   --
   --       vim.keymap.set("n", "<leader>ts", function()
   --          require("neotest").summary.toggle()
   --       end, { desc = "Toggle test summary" })
   --    end,
   -- },

   -- -- REPL interactivo para Python
   -- {
   --    "Vigemus/iron.nvim",
   --    config = function()
   --       local iron = require("iron.core")
   --
   --       iron.setup({
   --          config = {
   --             scratch_repl = true,
   --             repl_definition = {
   --                python = {
   --                   command = { "python3" },
   --                   format = require("iron.fts.common").bracketed_paste,
   --                },
   --             },
   --             repl_open_cmd = require("iron.view").bottom(40),
   --          },
   --          keymaps = {
   --             send_motion = "<space>sc",
   --             visual_send = "<space>sc",
   --             send_file = "<space>sf",
   --             send_line = "<space>sl",
   --             send_until_cursor = "<space>su",
   --             send_mark = "<space>sm",
   --             mark_motion = "<space>mc",
   --             mark_visual = "<space>mc",
   --             remove_mark = "<space>md",
   --             cr = "<space>s<cr>",
   --             interrupt = "<space>s<space>",
   --             exit = "<space>sq",
   --             clear = "<space>cl",
   --          },
   --          highlight = {
   --             italic = true,
   --          },
   --          ignore_blank_lines = true,
   --       })
   --
   --       vim.keymap.set("n", "<leader>rs", "<cmd>IronRepl<cr>", { desc = "Start REPL" })
   --       vim.keymap.set("n", "<leader>rr", "<cmd>IronRestart<cr>", { desc = "Restart REPL" })
   --       vim.keymap.set("n", "<leader>rf", "<cmd>IronFocus<cr>", { desc = "Focus REPL" })
   --       vim.keymap.set("n", "<leader>rh", "<cmd>IronHide<cr>", { desc = "Hide REPL" })
   --    end,
   -- },

   -- -- Snippets útiles para Python
   -- {
   --    "rafamadriz/friendly-snippets",
   --    event = "InsertEnter",
   -- }
}
